### ISSUE TITLE
Chef Cookbook installer for Mattermost

### ISSUE THREAD

**Issue by jasonblais** [verifi-inc/mattermost#16]
Hey @kcorupe ,

First, I want to thank for your contribution for creating a Chef Cookbook installer for Mattermost: https://github.com/verifi-inc/mattermost

It has gained interest within the community, and really appreciate your continued help maintaining the project: https://github.com/verifi-inc/mattermost/pull/12

Recently, @magicknot forked this repository and made a few updates to support Mattermost v4.1.0 (the latest release), including new configuration options. The repository can be found here (note that your name is included as authors): https://github.com/ist-dsi/mattermost-cookbook

Wondering if you'd have a preference on the best way for maintaining the Cookbook installer so the community is able to download most recent updates?

Hope you're doing well!

Jason
Mattermost, Inc.

**Comment by kcorupe** [comment]
@magicknot's fork is available on chef supermarket here: https://supermarket.chef.io/cookbooks/mattermost-cookbook

I'll be running mattermost from docker in the near future.

Since this cookbook is now outdated with with @magicknots installer being the latest and also supporting more distributions I think it be best to mark this one as deprecated. I can update the README to signify that.

**Comment by jasonblais** [comment]
Awesome!!

That sounds good, if you'd like to make that note in the README, we'll also make updates on our side.
